### ISSUE TITLE
Does the code of  StimulusVerification support the stimulus_type "both", i.e., "context+social"?

### ISSUE THREAD

**Issue by hilbert9221** [ApeironY/Modular-Trajectory-Prediction-Toolkit#4]
Thank you for providing the wonderful codes for modular trajectory prediction. I am trying to develop my code based on StimulusVerification. In Table 1 of the paper, it is possible to jointly consider the stimuls types "context" and "social". However, in the code, there is no such choice for "both". Since "context+social" achieves the most significant improvement in the paper, I wonder if it is easy to do this within the code you provide. Thanks in advance!

**Comment by ApeironY** [comment]
Hi, thank you for your interest in our work!

In `verify_predictions.py`, a list named `all_verification_scores` is defined at L61, which is used later to store both context and social compatibility scores, the scores are then added together in L235, *i.e.* verification with context+social.

Hope this answers your question.

**Comment by hilbert9221** [comment]
Thanks for you reply! It seems that I should train "model+context" and "model+social" separately, and then combine them in `verify_predictions.py`. I will try that.
